# Generated by Django 5.0.12 on 2025-03-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, unique=True)),
                ('password_hash', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('role', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
