# Generated by Django 5.0.12 on 2025-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReferences',
            fields=[
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_name', models.CharField(max_length=100)),
                ('reference_contact', models.CharField(max_length=50)),
                ('reference_email', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee_references',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=100)),
                ('EH_start_date', models.DateField()),
                ('EH_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employment_history',
                'managed': False,
            },
        ),
    ]
