# Generated by Django 5.0.12 on 2025-03-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('middle_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('last_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('current_address', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('permanent_address', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('passport_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('work_permit_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('work_permit_issue_date', models.DateField(blank=True, null=True)),
                ('work_permit_expiry_date', models.DateField(blank=True, null=True)),
                ('sin_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('sin_issue_date', models.DateField(blank=True, null=True)),
                ('sin_expiry_date', models.DateField(blank=True, null=True)),
                ('driving_license_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('driving_license_issue_date', models.DateField(blank=True, null=True)),
                ('driving_license_expiry_date', models.DateField(blank=True, null=True)),
                ('criminal_record_check', models.BooleanField()),
                ('date_of_joining', models.DateField()),
                ('designation', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('is_deleted', models.BooleanField()),
                ('current_email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, unique=True)),
                ('permanent_email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, unique=True)),
                ('current_phone', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15)),
                ('permanent_phone', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageappImagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('image_data', models.BinaryField(max_length='max')),
            ],
            options={
                'db_table': 'imageapp_imagemodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
            ],
            options={
                'db_table': 'leaves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payslips',
            fields=[
                ('payslip_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_date', models.DateField()),
            ],
            options={
                'db_table': 'payslips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, unique=True)),
                ('password_hash', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('role', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
