# Generated by Django 5.0.12 on 2025-03-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_admin', '0002_employeereferences_employmenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDetails',
            fields=[
                ('academic_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('institution', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('year_of_passing', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10)),
                ('grade', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'academic_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrivingDetails',
            fields=[
                ('driving_id', models.AutoField(primary_key=True, serialize=False)),
                ('driving_license_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('driving_license_issue_date', models.DateField(blank=True, null=True)),
                ('driving_license_expiry_date', models.DateField(blank=True, null=True)),
                ('driving_license_document', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'driving_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeContactDetails',
            fields=[
                ('employee_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_address', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('permanent_address', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('current_email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('permanent_email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('current_phone', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15)),
                ('permanent_phone', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15)),
            ],
            options={
                'db_table': 'employee_contact_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtherDocuments',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_letter_document', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('contract_letter_document', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'other_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PassportDetails',
            fields=[
                ('passport_id', models.AutoField(primary_key=True, serialize=False)),
                ('passport_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('passport_document', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'passport_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SinDetails',
            fields=[
                ('sin_id', models.AutoField(primary_key=True, serialize=False)),
                ('sin_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('sin_issue_date', models.DateField(blank=True, null=True)),
                ('sin_expiry_date', models.DateField(blank=True, null=True)),
                ('sin_document', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'sin_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkPermitDetails',
            fields=[
                ('work_permit_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_permit_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('work_permit_issue_date', models.DateField(blank=True, null=True)),
                ('work_permit_expiry_date', models.DateField(blank=True, null=True)),
                ('work_permit_document', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'work_permit_details',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ImageappImagemodel',
        ),
    ]
