# Generated by Django 5.0.12 on 2025-03-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDetails',
            fields=[
                ('academic_id', models.AutoField(primary_key=True, serialize=False)),
                ('degree', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('institution', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('year_of_passing', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10)),
                ('grade', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'academic_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DrivingDetails',
            fields=[
                ('driving_id', models.AutoField(primary_key=True, serialize=False)),
                ('driving_license_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('driving_license_issue_date', models.DateField(blank=True, null=True)),
                ('driving_license_expiry_date', models.DateField(blank=True, null=True)),
                ('driving_license_document', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'driving_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeContactDetails',
            fields=[
                ('employee_contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_address', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('permanent_address', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('current_email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('permanent_email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('current_phone', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15)),
                ('permanent_phone', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15)),
            ],
            options={
                'db_table': 'employee_contact_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeReferences',
            fields=[
                ('reference_id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('reference_contact', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('reference_email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('relationship', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'employee_references',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('middle_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('last_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('gender', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('nationality', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('criminal_record_check', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10)),
                ('date_of_joining', models.DateField()),
                ('designation', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('is_deleted', models.IntegerField()),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('job_title', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('eh_start_date', models.DateField(blank=True, db_column='EH_start_date', null=True)),
                ('eh_end_date', models.DateField(blank=True, db_column='EH_end_date', null=True)),
            ],
            options={
                'db_table': 'employment_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
                ('l_apply_date', models.DateField(db_column='L_apply_date')),
                ('l_start_date', models.DateField(db_column='L_start_date')),
                ('l_end_date', models.DateField(db_column='L_end_date')),
                ('leave_reason', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('l_status', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='L_status', max_length=20)),
            ],
            options={
                'db_table': 'leaves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtherDocuments',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_letter_document', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('contract_letter_document', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('profile_image', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'other_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PassportDetails',
            fields=[
                ('passport_id', models.AutoField(primary_key=True, serialize=False)),
                ('passport_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('passport_document', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'passport_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payslips',
            fields=[
                ('payslip_id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_generated', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payslips',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SinDetails',
            fields=[
                ('sin_id', models.AutoField(primary_key=True, serialize=False)),
                ('sin_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('sin_issue_date', models.DateField(blank=True, null=True)),
                ('sin_expiry_date', models.DateField(blank=True, null=True)),
                ('sin_document', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'sin_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, unique=True)),
                ('password_hash', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('u_role', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkPermitDetails',
            fields=[
                ('work_permit_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_permit_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('work_permit_issue_date', models.DateField(blank=True, null=True)),
                ('work_permit_expiry_date', models.DateField(blank=True, null=True)),
                ('work_permit_document', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'work_permit_details',
                'managed': False,
            },
        ),
    ]
